image: ruby:2.6

rspec:
  stage: test
  variables:
    LANG: C.UTF-8
    LC_ALL: C.UTF-8
  before_script:
  - apt-get update
  - apt-get install -y cmake
  - locale
  - locale -a
  script:
  - bin/setup
  - bundle exec rspec
