image: ruby:2.6

services:
  - docker:19.03.1-dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

rspec:
  stage: test
  variables:
    LANG: C.UTF-8
    LC_ALL: C.UTF-8
    CI_BUILDS_DIR: /builds/$CI_PROJECT_PATH/dosuken-test
  before_script:
  - apt-get update
  - apt-get install -y cmake docker.io
  - docker info
  - pwd
  script:
  - bin/setup
  - bundle exec rspec
