application: awesome-app

groups:
  backend:
    - db

global:
  environment:
    image: common-ruby-on-rails

services:
  web:
    repo: https://gitlab.com/gitlab-org/gitlab-ce.git
    port: 1234
  db:
    port: 9999
