application: awesome-app

environment:
  type: local

variables:
  POSTGRES_VERSION: 1.2.3

groups:
  backend:
    - db

services:
  web:
    repo: https://github.com/dosuken123/state_machine.git
    port: 1234
  db:
    port: 9999
