application: awesome-app

groups:
  backend:
    - db

global:
  environment:
    image: common-ruby-on-rails

services:
  web:
    repo: https://github.com/dosuken123/state_machine.git
    port: 1234
  db:
    port: 9999
