application: awesome-app

environment:
  type: local

variables:
  POSTGRES_VERSION: 1.2.3

groups:
  backend:
    - web
    - sidekiq

services:
  web:
    repo: https://github.com/dosuken123/state_machine.git
    port: 1234
  sidekiq:
    repo: https://github.com/mperham/sidekiq.git
  db:
    port: 9999
